services:
  ecommerce:
    build: ./
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.development
volumes:
  postgres-data:
